Dvocifren_broj = int(input("Unesi dvocifren broj: "))
Prva_cifra = (Dvocifren_broj // 10)
Druga_cifra = (Dvocifren_broj % 10)
print("Prva cifra je:", Prva_cifra)
print("Druga cifra je:", Druga_cifra)
